### ISSUE TITLE
Drive Module

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceTeam/roveberrypy#28]
Make the rover move!
- [x] Receive joystick input
- [x] Braking
- [x] Skid-steer operation (optional: could add additional mode for rc car style control)
- [ ] Easy to adjust throttle limiting. (Through the web UI?)
- [x] Send messages to embeded drive controller.
- [ ] Allow webui to change control mode (rpm, torque, pwm)
- [x] Switch to non-linear curves for input.

**Comment by ausshir** [comment]
We have the capability to control motors with closed-loop Speed and Current, and open-loop Duty Cycle controls. It would be great if we had some ideas on how these should actually be used!
